version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: docker
    directory: /  # Where to look for a `Dockerfile`
    schedule:
      interval: daily

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /  # Where to look for a `.github/workflows` folder
    schedule:
      interval: daily
